### ISSUE TITLE
help cant get mdraw.exe to run

### ISSUE THREAD

**Issue by ghost** [Makeblock-official/mDrawBot#36]
keep getting the follow error when trying to run mraw.exe after downloading the windows zip:
 File "mDraw.py", line 5, in <module>
  File "D:\Python34\lib\site-packages\zipextimporter.py", line 116, in load_module
zipimport.ZipImportError: can't find module SvgParser

**Comment by ghost** [comment]
SO....... got the file unzipped and now whenever i go to run the mdraw.exe file all i get is this:
Traceback (most recent call last):
  File "mDraw.py", line 723, in <module>
  File "mDraw.py", line 46, in **init**
  File "mDraw.py", line 54, in initUI
  File "mDraw.py", line 484, in refreshCom
  File "D:\mDraw_python\mDraw\SerialCom.py", line 33, in serialList
  File "D:\Python34\lib\site-packages\serial\serialwin32.py", line 38, in **init**
  File "D:\Python34\lib\site-packages\serial\serialutil.py", line 282, in **init**
  File "D:\Python34\lib\site-packages\serial\serialwin32.py", line 82, in open
  File "D:\Python34\lib\site-packages\serial\serialwin32.py", line 202, in _reconfigurePort
ValueError: Cannot configure port, some setting was wrong. Original message: OSError(22, 'Incorrect function.', None, 1)

Can someone please diagnose what this means???
