### ISSUE TITLE
mDrawGui with Ubuntu

### ISSUE THREAD

**Issue by Buitani** [Makeblock-official/mDrawBot#66]
Started mDrawGui  with
`sudo python3 mDraw.py`

When I want to open mDrawGui  it looks fine, but in the terminal I got this message:

```shell
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
/home/bob/Downloads/mDrawBot-master/mDrawGui/mDraw.py:130: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  self.refreshThread.setDaemon(True)
Traceback (most recent call last):
  File "/home/bob/Downloads/mDrawBot-master/mDrawGui/ScaraRobot.py", line 168, in paint
    painter.drawEllipse(x1-5,y1-5,10,10)
TypeError: arguments did not match any overloaded call:
  drawEllipse(self, QRectF): argument 1 has unexpected type 'float'
  drawEllipse(self, QRect): argument 1 has unexpected type 'float'
  drawEllipse(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawEllipse(self, Union[QPointF, QPoint], float, float): argument 1 has unexpected type 'float'
  drawEllipse(self, QPoint, int, int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "/home/bob/Downloads/mDrawBot-master/mDrawGui/ScaraRobot.py", line 168, in paint
    painter.drawEllipse(x1-5,y1-5,10,10)

``` 
mDrawGui does not work properly. I cant load files.

Any suggestions what I can do?

**Comment by ajxn** [comment]
There are some calls to methods like drawEllipse(), drawLines() etc that take integers as arguments, but the call is done with float type.   That does make it not to work properly.

I will push fixes fr them in my fork.  I will push a push request here later.
